version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: ponder-postgres-db
    environment:
      POSTGRES_USER: ponder-user
      POSTGRES_PASSWORD: ponder-pass
      POSTGRES_DB: ponder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
