import { createSchema } from "@ponder/core";


export default createSchema((p) => ({
  Account: p.createTable({
    id: p.string(),
    isController: p.boolean(),
    ownedMarkets: p.many("Market.ownerId"),
    trades: p.many("Trade.buyerId"),
    createdFees: p.many("ClaimedCreatorFee.creatorId"),
    ownerFees: p.many("ClaimedOwnerFee.beneficiaryId"),
    reflectionFees: p.many("ClaimedReflectionFee.beneficiaryId"),
    rewards: p.many("ClaimedReward.beneficiaryId"),
    transferEvents: p.many("OwnershipTransferred.newOwnerId"),
    nftBalance: p.bigint(),
    nftApprovals: p.many("Approval.owner"),
    nftTransferFromEvents: p.many("TransferEvent.from"),
    nftTransferToEvents: p.many("TransferEvent.to"),
  }),
  Market: p.createTable({
    id: p.string(),
    marketId: p.bigint(),
    ownerId: p.string().references("Account.id"),
    owner: p.one("ownerId"),
    trades: p.many("Trade.marketId"),
    bonuses: p.many("BonusAdded.marketId"),
    rewards: p.many("RewardsOffered.marketId"),
  }),
  Trade: p.createTable({
    id: p.string(),
    marketId: p.string().references("Market.id"),
    buyerId: p.string().references("Account.id"),
    sellerId: p.string().references("Account.id"),
    qty: p.bigint(),
    pricePaid: p.bigint(),
    protocolFee: p.bigint(),
    ownerFee: p.bigint(),
    creatorFee: p.bigint(),
    rewardFee: p.bigint(),
    reflectionFee: p.bigint(),
    newSupply: p.bigint(),
    dividendsAdded: p.bigint(),
    priceReceived: p.bigint(),
    buyer: p.one("buyerId"),
    seller: p.one("sellerId"),
    market: p.one("marketId"),
  }),
  BonusAdded: p.createTable({
    id: p.string(),
    amount: p.bigint(),
    marketId: p.string().references("Market.id"),
    market: p.one("marketId"),
  }),
  ClaimedCreatorFee: p.createTable({
    id: p.string(),
    creatorId: p.string().references("Account.id"),
    beneficiaryId: p.string().references("Account.id"),
    claimedFees: p.bigint(),
    creator: p.one("creatorId"),
    beneficiary: p.one("beneficiaryId"),
  }),
  ClaimedOwnerFee: p.createTable({
    id: p.string(),
    marketId: p.string().references("Market.id"),
    beneficiaryId: p.string().references("Account.id"),
    claimedFees: p.bigint(),
    market: p.one("marketId"),
    beneficiary: p.one("beneficiaryId"),
  }),
  ClaimedReflectionFee: p.createTable({
    id: p.string(),
    marketId: p.string().references("Market.id"),
    beneficiaryId: p.string().references("Account.id"),
    claimedFees: p.bigint(),
    market: p.one("marketId"),
    beneficiary: p.one("beneficiaryId"),
  }),
  ClaimedReward: p.createTable({
    id: p.string(),
    marketId: p.string().references("Market.id"),
    beneficiaryId: p.string().references("Account.id"),
    claimedRewards: p.bigint(),
    market: p.one("marketId"),
    beneficiary: p.one("beneficiaryId"),
  }),
  OwnershipTransferred: p.createTable({
    id: p.string(),
    previousOwnerId: p.string().references("Account.id"),
    newOwnerId: p.string().references("Account.id"),
    previousOwner: p.one("previousOwnerId"),
    newOwner: p.one("newOwnerId"),
  }),
  RewardsOffered: p.createTable({
    id: p.string(),
    marketId: p.string().references("Market.id"),
    amount: p.bigint(),
    pendingRewardsInHand: p.bigint(),
    market: p.one("marketId"),
  }),
  Approval: p.createTable({
    id: p.string(),
    owner: p.string().references("Account.id"),
    approved: p.string().references("Account.id"),
    tokenId: p.bigint(),
    ownerId: p.one("owner"),
  }),
  ApprovalForAll: p.createTable({
    id: p.string(),
    owner: p.string().references("Account.id"),
    operator: p.string().references("Account.id"),
    approved: p.boolean(),
  }),
  BatchMetadataUpdate: p.createTable({
    id: p.string(),
    fromTokenId: p.bigint(),
    toTokenId: p.bigint(),
  }),
  MetadataUpdate: p.createTable({
    id: p.string(),
    tokenId: p.bigint(),
  }),
  TransferEvent: p.createTable({
    id: p.string(),
    from: p.string().references("Account.id"),
    to: p.string().references("Account.id"),
    tokenId: p.bigint(),
    fromId: p.one("from"),
    toId: p.one("to"),
  }),
}));

